### Criar Sala
POST http://localhost:8080/api/room
Content-Type: application/json

{
  "room": "Sala Reunião 01"
}

###

### Criar Usuário
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "João Gabriel",
  "email": "joao.gabriel@email.com",
  "department": "TI"
}

###

### Criar Reserva
POST http://localhost:8080/api/booking
Content-Type: application/json

{
  "title": "Reunião de Alinhamento",
  "data": "2025-10-24",
  "hour_inicial": "09:00:00",
  "hour_final": "10:00:00",
  "emailUser": "joao.gabriel@email.com",
  "roomName": "Sala Reunião 01"
}
