### Criar Sala
POST http://localhost:8080/api/room
Content-Type: application/json

{
  "emailUser": "joao.gabriel@email.com",
  "room": "Sala Reunião 02"
}



### Criar Usuário
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "João Gabriel",
  "email": "joao.gabriel@email.com",
  "department": "TI"
}

###

### Criar Reserva
POST http://localhost:8080/api/booking
Content-Type: application/json

{
  "title": "Reunião de Alinhamento",
  "data": "2025-10-24",
  "hour_inicial": "14:00:00",
  "hour_final": "15:00:00",
  "emailUser": "joao.gabriel@email.com",
  "roomName": "Sala Reunião 01"
}


### Consultar as reservas
GET http://localhost:8080/api/booking
Content-Type: application/json

{
  "emailUser": "joao.gabriel@email.com",
  "room": "Sala Reunião 01"
}


### Consultar as reservas
GET http://localhost:8080/api/booking/all
Content-Type: application/json

{

}


### Editar reserva
PATCH http://localhost:8080/api/booking/edit/1
Content-Type: application/json

{
  "title": "Reunião de Alinhamento 3",
  "data": "2025-10-24",
  "hour_inicial": "11:00:00",
  "hour_final": "12:00:00"
}